apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - headlamp/helmrelease.yaml
  - headlamp/ingress.yaml
  - adguard/adguard.yaml
  - metallb/kustomizations.yaml
  - cert-manager/kustomizations.yaml
  - traefik/middleware.yaml
